name: CI

on:
  [pull_request, push]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: npm ci

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: "${{ env.GITHUB_TOKEN }}"
          environment: test
          initial_status: success

      - name: Delete Deployment
        uses: ./
        with:
          token: ${{ env.GITHUB_TOKEN }}
          environment: test
    