name: CI

on:
  [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - name: npm ci
        run: npm ci
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm i
      - name: lint
        run: npm run lint
      - name: run tests
        run: npm test
      - name: create GitHub deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: test
          initial_status: success
      - name: delete deployment
        uses: ./
        with:
          token: ${{ github.token }}
          environment: test
    