name: CI

on:
  [pull_request, push]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - name: npm ci
        run: npm ci
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - name: npm install
        run: npm i
      - name: lint
        run: npm run lint
      - name: create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: "${{ env.GITHUB_TOKEN }}"
          environment: test
          initial_status: success
      - name: delete deployment
        uses: ./
        with:
          token: ${{ env.GITHUB_TOKEN }}
          environment: test
    